import { StyleSheet } from 'react-native';

export const colors = {
  primary: '#06C167',
  primaryDark: '#04A65B',
  background: '#121212',
  backgroundSecondary: '#1E1E1E',
  white: '#FFFFFF',
  text: '#EDEDED',
  textSecondary: '#B3B3B3',
  success: '#06C167',
  error: '#FF6B6B',
  warning: '#FFB74D',
  info: '#2196F3',
  veg: '#234C2C',
  vegText: '#8AFFA0',
  nonVeg: '#4C1C1C',
  nonVegText: '#FF8080',
  popular: '#4D3B1A',
  popularText: '#FFD54F',
  new: '#1A3B4D',
  newText: '#4FC3F7',
};

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  safeArea: { flex: 1, backgroundColor: colors.background },
  contentContainer: { flex: 1, padding: 16, backgroundColor: colors.background },
  header: {
    backgroundColor: colors.backgroundSecondary,
    paddingHorizontal: 20,
    paddingVertical: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  headerTitle: { fontSize: 20, fontWeight: '600', color: colors.primary },
  headerButton: { backgroundColor: colors.primary, paddingHorizontal: 16, paddingVertical: 10, borderRadius: 20 },
  headerButtonText: { color: colors.white, fontWeight: 'bold', fontSize: 14 },
  filterBarContainer: { height: 50, marginBottom: 15 },
  filterButton: {
    backgroundColor: colors.backgroundSecondary,
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 10,
  },
  filterButtonActive: {
    backgroundColor: colors.primary,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.6,
    shadowRadius: 4,
    elevation: 3,
  },
  filterButtonText: { fontSize: 14, fontWeight: '500', color: colors.textSecondary },
  filterButtonTextActive: { color: colors.white },
  counter: {
    backgroundColor: colors.backgroundSecondary,
    padding: 15,
    borderRadius: 10,
    marginBottom: 15,
    alignItems: 'center',
    borderColor: colors.primary,
    borderWidth: 1,
  },
  counterText: { fontSize: 16, fontWeight: 'bold', color: colors.primary },
  menuContainer: { flex: 1 },
  menuCard: {
    backgroundColor: colors.backgroundSecondary,
    padding: 18,
    borderRadius: 15,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 6,
  },
  cardTitle: { fontSize: 18, fontWeight: '600', color: colors.primary, marginBottom: 8 },
  cardDescription: { fontSize: 14, color: colors.textSecondary, marginBottom: 10, lineHeight: 20 },
  cardTags: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 10 },
  tag: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12, marginRight: 6, marginBottom: 4 },
  tagText: { fontSize: 12, fontWeight: '600' },
  tagVeg: { backgroundColor: colors.veg },
  tagVegText: { color: colors.vegText },
  tagNonVeg: { backgroundColor: colors.nonVeg },
  tagNonVegText: { color: colors.nonVegText },
  tagPopular: { backgroundColor: colors.popular },
  tagPopularText: { color: colors.popularText },
  tagNew: { backgroundColor: colors.new },
  tagNewText: { color: colors.newText },
  cardPrice: { fontSize: 18, fontWeight: 'bold', color: colors.primary, marginTop: 8 },
  formContainer: { flex: 1, padding: 20 },
  formTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.primary,
    marginBottom: 20,
    textAlign: 'center',
  },
  inputGroup: { marginBottom: 20 },
  label: { fontSize: 16, fontWeight: '600', color: colors.text, marginBottom: 8 },
  textInput: {
    borderWidth: 1,
    borderColor: colors.primaryDark,
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    backgroundColor: '#1E1E1E',
    color: colors.white,
  },
  multilineInput: { height: 80, textAlignVertical: 'top' },
  picker: { borderWidth: 1, borderColor: colors.primaryDark, borderRadius: 8, backgroundColor: '#1E1E1E' },
  numericInput: {
    borderWidth: 1,
    borderColor: colors.primaryDark,
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    backgroundColor: '#1E1E1E',
    color: colors.white,
  },
  submitButton: {
    backgroundColor: colors.primary,
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 25,
    alignItems: 'center',
    marginTop: 20,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    elevation: 6,
  },
  submitButtonText: { color: colors.white, fontSize: 18, fontWeight: 'bold' },
  statsContainer: {
    backgroundColor: colors.backgroundSecondary,
    padding: 15,
    borderRadius: 10,
    marginBottom: 15,
  },
  statsTitle: { fontSize: 16, fontWeight: 'bold', color: colors.primary, marginBottom: 10 },
  statItem: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 5 },
  statLabel: { fontSize: 14, color: colors.text },
  statValue: { fontSize: 14, fontWeight: '600', color: colors.textSecondary },
  emptyState: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 40 },
  emptyStateText: { fontSize: 16, color: colors.textSecondary, textAlign: 'center', marginTop: 10 },
  tabBar: {
    backgroundColor: colors.backgroundSecondary,
    borderTopColor: '#2c2c2c',
    borderTopWidth: 1,
    paddingTop: 5,
    paddingBottom: 5,
    height: 60,
  },
  tabLabel: { fontSize: 12, fontWeight: '600', color: colors.primary },
  tabIcon: { fontSize: 24, color: colors.primary },
});